name: fluda
description: Fluda is a library which makes Flutter application development faster and easier. It makes your code clean and easy to read.
version: 1.1.0
homepage: https://simonpham.github.io/fluda
repository: https://github.com/simonpham/fluda

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

