name: fluda
description: Fluda is a library which makes Flutter application development faster and easier. It makes your code clean and easy to read.
version: 0.2.0
homepage: https://fluda.simonit.dev

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^5.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

